# kubernetes/deploykey-secret.yaml
# ---
# Template de Secret Kubernetes para a chave SSH de deploy (ESBOÇO - NÃO FUNCIONAL)
# Este arquivo é um template base e NÃO ESTÁ FUNCIONAL. Requer ajustes e validação.
# É um ponto de partida para a implementação final do Secret Kubernetes.
# *** IMPORTANTE: NÃO INCLUA A CHAVE SSH DIRETAMENTE NESTE ARQUIVO EM PRODUÇÃO! ***
# Use um método seguro para injetar o valor da chave (ex: variável de ambiente, ferramenta de secrets).
# Este template é apenas para referência de como o Secret deve ser estruturado.
# Criado por: Elias Andrade - Maringá Paraná - 10/03/2025
# ---
apiVersion: v1
kind: Secret
metadata:
  name: deploykey # Nome do Secret - Referenciado no Deployment (projetojumpad-deployment.yaml)
  # namespace: seu-namespace # Descomente e ajuste se precisar em um namespace específico
type: kubernetes.io/ssh-auth # Tipo do Secret: para autenticação SSH

# *** IMPORTANTE: SUBSTITUA 'SUA_CHAVE_SSH_PRIVADA_AQUI' PELO CONTEÚDO REAL DA SUA CHAVE SSH PRIVADA ***
# *** NUNCA FAÇA ISSO DIRETAMENTE EM PRODUÇÃO! USE UM MÉTODO SEGURO PARA INJETAR A CHAVE ***
data:
  ssh-privatekey: "FUTURACHAVEPRIVADA" # Chave SSH privada (BASE64 ENCODED)

# ---
# INSTRUÇÕES IMPORTANTES PARA CRIAR O SECRET CORRETAMENTE (FORA DESTE ARQUIVO):
# 1.  NÃO EDITE ESTE ARQUIVO DIRETAMENTE PARA INSERIR SUA CHAVE SSH PRIVADA EM PRODUÇÃO.
# 2.  USE O COMANDO 'kubectl create secret generic' PARA CRIAR O SECRET DE FORMA SEGURA A PARTIR DA LINHA DE COMANDO OU DE UM SCRIPT.
# 3.  EXEMPLO DE COMO CRIAR O SECRET USANDO UMA VARIÁVEL DE AMBIENTE (PARA TESTES LOCAIS - NÃO PRODUÇÃO):
#
#     export DEPLOY_SSH_KEY="$(cat ~/.ssh/id_rsa)" # Exemplo: chave SSH padrão (~/.ssh/id_rsa)
#     kubectl create secret generic deploykey \
#       --from-literal=ssh-privatekey="$DEPLOY_SSH_KEY" \
#       --type=kubernetes.io/ssh-auth -n seu-namespace # Substitua 'seu-namespace'
#
# 4.  EM PRODUÇÃO, CONSIDERE USAR UM GERENCIADOR DE SECRETS (VAULT, AWS SECRETS MANAGER, AZURE KEY VAULT, ETC.) PARA INJETAR A CHAVE SSH DE FORMA MAIS SEGURA.